version: '3'

services:
    http_server:
        build:
            context: ./src/http_server
            dockerfile: Dockerfile
        container_name: code-battle-http-server        

    python:
        build: 
            context: ./src/python
            dockerfile: Dockerfile
        container_name: code-battle-python
        env_file: .env
        environment:
            - NAME=python
        volumes:
            - ./reports:/reports
            - ./apk_cache:/apk_cache
        
    
    pypy:
        build: 
            context: ./src/pypy
            dockerfile: Dockerfile
        container_name: code-battle-pypy
        env_file: .env
        environment:
            - NAME=pypy
        volumes:
            - ./reports:/reports
            - ./apk_cache:/apk_cache
        
    
    golang:
        build:
            context: ./src/golang
            dockerfile: Dockerfile
        container_name: code-battle-golang
        env_file: .env
        environment:
            - NAME=golang
        volumes:
            - ./reports:/reports
            - ./apk_cache:/apk_cache
        

    php:
        build:
            context: ./src/php
            dockerfile: Dockerfile
        container_name: code-battle-php
        env_file: .env
        environment:
            - NAME=php
        volumes:
            - ./reports:/reports
            - ./apk_cache:/apk_cache
        

    node:
        build:
            context: ./src/node
            dockerfile: Dockerfile
        container_name: code-battle-node
        env_file: .env
        environment:
            - NAME=node
        volumes:
            - ./reports:/reports
            - ./apk_cache:/apk_cache

    csharp:
        build:
            context: ./src/csharp
            dockerfile: Dockerfile
        container_name: code-battle-csharp
        env_file: .env
        environment:
            - NAME=csharp
        volumes:
            - ./reports:/reports            
        

    parser:
        build:
            context: ./src/parser
            dockerfile: Dockerfile
        container_name: code-battle-parser
        env_file: .env
        environment:
            - NAME=parser
            - REPORTS=/reports
        volumes:
            - ./reports:/reports

